### ISSUE TITLE
Easiness to merge with existing applications

### ISSUE THREAD

**Issue by ramymagdy-rm** [Wanderson-Magalhaes/Simple_PySide_Base#3]
Hi, first thanks for the time saver simple base. However, having some comments about the pythonic interpretation which can be subjective to the perspective. The following are suggestions for better usage of the repository.
- It wasn't so easy merging the UI base with an existing application, that was due to a circular import.
- there are some pythonic oop bugs or better ways to approach the solution
- no need for global variables since they are already included in the Functions class
- too many comments with no added details than the declared already in functions names
- In the repository, the credits are for the writer (Wanderson M. Pimenta), yet the repo doesn't follow any licensing, It would be helpful to include a license, MIT recommended.
- the skin color is somehow limited, it would be nicer to include a light skin besides the dark one.

besides those comments the repo is really helpful and time saver, thanks a lot!

**Comment by Wanderson-Magalhaes** [comment]
Thank you for the tips @ramymagdy-rm !
The aim of this project was to serve as inspiration for new projects, showing that it is possible to create modern interfaces using Python and its official interface module (PySide2). This was a personal project that I decided to share publicly.
Feel free to use as inspiration, use in your projects, fix bugs and improve as needed.
A license was added to the project and a new file called "app_modules.py" to call all additional modules dependent on the interface of the application.
If you want to use it commercially, I recommend reading it on the official Qt website because there are limitations:
[](https://doc.qt.io/qtforpython/licenses.html)
